import React, { useCallback, useEffect, useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/hooks/useAuth';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { toast } from 'sonner';
import {
  BookOpen,
  CalendarDays,
  GraduationCap,
  Layers,
  Link2,
  Loader2,
  LogOut,
  MessagesSquare,
} from 'lucide-react';
import { getSubjectLabel } from '@/utils/subjectColors';

interface Props {
  language: 'ar' | 'en';
  onSignOut: () => void;
}

interface StudentSummary {
  userId: string;
  name: string;
  subject: string | null;
  educationLevel: string | null;
  conversations: number;
  flashcardSets: number;
  studyPlans: number;
  lastActivity: string | null;
  bySubject: Record<string, number>;
}

const dict = {
  ar: {
    title: 'لوحة ولي الأمر',
    subtitle: 'متابعة تقدّم المتعلم — عرض للقراءة فقط',
    linkTitle: 'اربط حسابك بالمتعلم',
    linkDesc: 'أدخل كود الدعوة الذي أنشأه المتعلم من صفحة «ربط ولي الأمر».',
    placeholder: 'كود الدعوة',
    link: 'ربط',
    linked: 'تم الربط بنجاح',
    invalid: 'الكود غير صحيح',
    expired: 'انتهت صلاحية الكود',
    usedAlready: 'الكود مستخدم من قبل',
    self: 'لا يمكنك ربط حسابك بنفسك',
    error: 'تعذّر إتمام الربط، حاول مرة أخرى',
    none: 'لا يوجد متعلم مرتبط بحسابك بعد.',
    conversations: 'محادثات التعلم',
    flashcards: 'مجموعات البطاقات',
    plans: 'الخطط الدراسية',
    last: 'آخر نشاط',
    subjectBreakdown: 'التوزيع حسب المادة',
    subject: 'المادة الحالية',
    signOut: 'تسجيل الخروج',
    noData: 'لا توجد بيانات بعد',
  },
  en: {
    title: 'Parent Dashboard',
    subtitle: 'Follow the learner’s progress — read only',
    linkTitle: 'Link your account to a learner',
    linkDesc: 'Enter the invite code generated by the learner.',
    placeholder: 'Invite code',
    link: 'Link',
    linked: 'Linked successfully',
    invalid: 'Invalid code',
    expired: 'Code expired',
    usedAlready: 'Code already used',
    self: 'You cannot link to yourself',
    error: 'Could not link, please try again',
    none: 'No learner linked yet.',
    conversations: 'Learning chats',
    flashcards: 'Flashcard sets',
    plans: 'Study plans',
    last: 'Last activity',
    subjectBreakdown: 'Breakdown by subject',
    subject: 'Current subject',
    signOut: 'Sign out',
    noData: 'No data yet',
  },
};

const ParentDashboard: React.FC<Props> = ({ language, onSignOut }) => {
  const txt = dict[language];
  const { user } = useAuth();
  const [code, setCode] = useState('');
  const [linking, setLinking] = useState(false);
  const [loading, setLoading] = useState(true);
  const [students, setStudents] = useState<StudentSummary[]>([]);

  const load = useCallback(async () => {
    if (!user) return;
    setLoading(true);
    const { data: links } = await supabase
      .from('parent_links')
      .select('student_id')
      .eq('parent_id', user.id);

    const ids = (links ?? []).map((l) => l.student_id);
    if (ids.length === 0) {
      setStudents([]);
      setLoading(false);
      return;
    }

    const [{ data: profiles }, { data: convos }, { data: cards }, { data: plans }] =
      await Promise.all([
        supabase.from('profiles').select('user_id, name, subject, education_level').in('user_id', ids),
        supabase.from('conversations').select('user_id, subject, updated_at').in('user_id', ids),
        supabase.from('flashcard_sets').select('user_id, created_at').in('user_id', ids),
        supabase.from('study_plans').select('user_id, subject, created_at').in('user_id', ids),
      ]);

    const summaries: StudentSummary[] = ids.map((id) => {
      const p = (profiles ?? []).find((x) => x.user_id === id);
      const myConvos = (convos ?? []).filter((c) => c.user_id === id);
      const myCards = (cards ?? []).filter((c) => c.user_id === id);
      const myPlans = (plans ?? []).filter((c) => c.user_id === id);
      const bySubject: Record<string, number> = {};
      myConvos.forEach((c) => {
        const key = c.subject || 'general';
        bySubject[key] = (bySubject[key] ?? 0) + 1;
      });
      const dates = [
        ...myConvos.map((c) => c.updated_at),
        ...myCards.map((c) => c.created_at),
        ...myPlans.map((c) => c.created_at),
      ].filter(Boolean) as string[];
      dates.sort();
      return {
        userId: id,
        name: p?.name ?? '—',
        subject: p?.subject ?? null,
        educationLevel: p?.education_level ?? null,
        conversations: myConvos.length,
        flashcardSets: myCards.length,
        studyPlans: myPlans.length,
        lastActivity: dates.length ? dates[dates.length - 1] : null,
        bySubject,
      };
    });

    setStudents(summaries);
    setLoading(false);
  }, [user]);

  useEffect(() => {
    load();
  }, [load]);

  const handleLink = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!code.trim()) return;
    setLinking(true);
    const { error } = await supabase.rpc('redeem_parent_invite', { _code: code.trim() });
    setLinking(false);
    if (error) {
      const msg = error.message || '';
      if (msg.includes('invalid_code')) toast.error(txt.invalid);
      else if (msg.includes('code_expired')) toast.error(txt.expired);
      else if (msg.includes('code_already_used')) toast.error(txt.usedAlready);
      else if (msg.includes('cannot_link_self')) toast.error(txt.self);
      else toast.error(txt.error);
      return;
    }
    toast.success(txt.linked);
    setCode('');
    load();
  };

  const fmtDate = (iso: string | null) =>
    iso ? new Date(iso).toLocaleDateString(language === 'ar' ? 'ar-EG' : 'en-US') : txt.noData;

  return (
    <div className="min-h-screen bg-background" dir={language === 'ar' ? 'rtl' : 'ltr'}>
      <header className="border-b border-border bg-card">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 py-4 flex items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl gradient-primary flex items-center justify-center">
              <GraduationCap className="w-5 h-5 text-primary-foreground" />
            </div>
            <div>
              <h1 className="text-lg font-bold">{txt.title}</h1>
              <p className="text-xs text-muted-foreground">{txt.subtitle}</p>
            </div>
          </div>
          <Button variant="ghost" size="sm" onClick={onSignOut}>
            <LogOut className="w-4 h-4 me-2" />
            {txt.signOut}
          </Button>
        </div>
      </header>

      <main className="max-w-5xl mx-auto px-4 sm:px-6 py-6 space-y-6">
        <Card className="p-5 space-y-4">
          <div>
            <h2 className="font-semibold flex items-center gap-2">
              <Link2 className="w-4 h-4" /> {txt.linkTitle}
            </h2>
            <p className="text-sm text-muted-foreground">{txt.linkDesc}</p>
          </div>
          <form onSubmit={handleLink} className="flex flex-col sm:flex-row gap-3">
            <Input
              value={code}
              onChange={(e) => setCode(e.target.value.toUpperCase())}
              placeholder={txt.placeholder}
              className="h-12 font-mono tracking-widest"
              dir="ltr"
              maxLength={12}
            />
            <Button type="submit" className="h-12 gradient-primary sm:w-40" disabled={linking}>
              {linking ? <Loader2 className="w-4 h-4 animate-spin" /> : txt.link}
            </Button>
          </form>
        </Card>

        {loading ? (
          <div className="flex justify-center py-12">
            <Loader2 className="w-6 h-6 animate-spin text-primary" />
          </div>
        ) : students.length === 0 ? (
          <Card className="p-8 text-center text-muted-foreground">{txt.none}</Card>
        ) : (
          students.map((s) => (
            <Card key={s.userId} className="p-5 space-y-5">
              <div className="flex items-center justify-between gap-3 flex-wrap">
                <h3 className="text-lg font-semibold">{s.name}</h3>
                {s.subject && (
                  <Badge variant="secondary">
                    {txt.subject}: {getSubjectLabel(s.subject as never, language)}
                  </Badge>
                )}
              </div>

              <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">
                {[
                  { icon: MessagesSquare, label: txt.conversations, value: s.conversations },
                  { icon: Layers, label: txt.flashcards, value: s.flashcardSets },
                  { icon: BookOpen, label: txt.plans, value: s.studyPlans },
                  { icon: CalendarDays, label: txt.last, value: fmtDate(s.lastActivity) },
                ].map((stat) => (
                  <div key={stat.label} className="rounded-xl border border-border bg-muted/40 p-4">
                    <stat.icon className="w-4 h-4 text-primary mb-2" />
                    <p className="text-xs text-muted-foreground">{stat.label}</p>
                    <p className="text-lg font-bold">{stat.value}</p>
                  </div>
                ))}
              </div>

              <div className="space-y-2">
                <p className="text-sm font-medium">{txt.subjectBreakdown}</p>
                {Object.keys(s.bySubject).length === 0 ? (
                  <p className="text-sm text-muted-foreground">{txt.noData}</p>
                ) : (
                  Object.entries(s.bySubject)
                    .sort((a, b) => b[1] - a[1])
                    .map(([subject, count]) => {
                      const max = Math.max(...Object.values(s.bySubject));
                      return (
                        <div key={subject} className="flex items-center gap-3">
                          <span className="text-sm w-28 shrink-0 truncate">
                            {getSubjectLabel(subject as never, language)}
                          </span>
                          <div className="flex-1 h-2 rounded-full bg-muted overflow-hidden">
                            <div
                              className="h-full rounded-full bg-primary"
                              style={{ width: `${(count / max) * 100}%` }}
                            />
                          </div>
                          <span className="text-sm text-muted-foreground w-8 text-end">{count}</span>
                        </div>
                      );
                    })
                )}
              </div>
            </Card>
          ))
        )}
      </main>
    </div>
  );
};

export default ParentDashboard;
